Repository TeamDevIU/Bot, pull requests merged in 2018-03, with the labels that each got.

#45 Vk bot
  VkGroupBot/.gitignore
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/main.js
  VkGroupBot/app/worker.js
Labels: review

#46 Development
  VkGroupBot/.gitignore
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/main.js
  VkGroupBot/app/worker.js
Labels: VK, review

#47 hot fix
  VkGroupBot/app/main.js
Labels: review

#48 HOT FIX
  VkGroupBot/app/main.js
Labels: review

#50 hot fix
  VkGroupBot/app/Bot/bot.js
  VkGroupBot/app/main.js
  VkGroupBot/package.json
Labels: review

#52 hot fix
  VkGroupBot/app/Handler/audio_message_handler.js
Labels: review

#61 Main server
  main-server/database.go
  main-server/main.go
Labels: MainServer, review

#60 Add logger, fix Bug
  VkGroupBot/.gitignore
  VkGroupBot/app/Handler/audio_message_handler.js
  VkGroupBot/app/Handler/handler_fabric.js
  VkGroupBot/app/Handler/message_parser.js
  VkGroupBot/app/Handler/text_message_handler.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/logger.js
  VkGroupBot/app/main.js
  VkGroupBot/app/tasks_distributor.js
  VkGroupBot/app/worker.js
  VkGroupBot/package-lock.json
  VkGroupBot/package.json
Labels: VK, review

#62 0.0.2
  .travis.yml
  .travis/DevOrMaster.sh
  .travis/deploy_rsa.enc
  .travis/forDevBranch.sh
  .travis/forMasterBranch.sh
  TgBot/Dockerfile
  VkGroupBot/.gitignore
  VkGroupBot/Dockerfile
  VkGroupBot/app/Handler/audio_message_handler.js
  VkGroupBot/app/Handler/handler_fabric.js
  VkGroupBot/app/Handler/message_parser.js
  VkGroupBot/app/Handler/text_message_handler.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/logger.js
  VkGroupBot/app/main.js
  VkGroupBot/app/tasks_distributor.js
  VkGroupBot/app/worker.js
  VkGroupBot/package-lock.json
  VkGroupBot/package.json
  docker-compose.yml
  main-server/Dockerfile
  main-server/database.go
  main-server/main.go
Labels: CD, MainServer, VK, review

#63 Update main.js
  VkGroupBot/app/main.js
Labels: review

#65 CD
  .travis.yml
  .travis/deploy.sh
  VkGroupBot/app/UserCommand/user_command_handler.js
  deploy_rsa.enc
Labels: CD, review

#67 Логирование
  TgBot/bot.py
  TgBot/handlers/base_handler.py
  TgBot/handlers/text_handler.py
  TgBot/handlers/voice_handler.py
  TgBot/log_config
  TgBot/main_server.py
Labels: review

#68 Add TgBot logs
  TgBot/bot.py
  TgBot/handlers/base_handler.py
  TgBot/handlers/text_handler.py
  TgBot/handlers/voice_handler.py
  TgBot/log_config
  TgBot/main_server.py
Labels: CD, Telegram, review

#69 TeamDevIU/Bot#56
  main-server/main.go
  main-server/main_test.go
Labels: review

#70 Add mainserver log
  main-server/main.go
  main-server/main_test.go
Labels: CD, MainServer, review

#71 bug fix
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: VK, bug, review

#72 bug fix vkbot
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: VK, bug, review

#73 Cosmetic
  main-server/main.go
Labels: review

#74 bug fix
  .travis/deploy.sh
  main-server/main.go
Labels: review

#75 TeamDevIU/Bot#58 TeamDevIU/Bot#30 Дополнено логирование, убрано дубли…
  TgBot/handlers/base_handler.py
  TgBot/handlers/text_handler.py
  TgBot/handlers/voice_handler.py
  TgBot/main_server.py
Labels: Telegram, review

#76 TgBot more logs :)
  TgBot/handlers/base_handler.py
  TgBot/handlers/text_handler.py
  TgBot/handlers/voice_handler.py
  TgBot/main_server.py
Labels: review

#77 Hotfix for logging
  main-server/main.go
Labels: review

#79 bug fix
  VkGroupBot/Dockerfile
  VkGroupBot/app/Handler/audio_message_handler.js
  VkGroupBot/app/Handler/base_handler.js
  VkGroupBot/app/Handler/handler_fabric.js
  VkGroupBot/app/Handler/message_parser.js
  VkGroupBot/app/Handler/text_message_handler.js
  VkGroupBot/app/UserCommand/base_command.js
  VkGroupBot/app/UserCommand/commands_fabric.js
  VkGroupBot/app/UserCommand/create_room_command.js
  VkGroupBot/app/UserCommand/roominfo_command.js
  VkGroupBot/app/UserCommand/rooms_list_command.js
  VkGroupBot/app/UserCommand/send_message_command.js
  VkGroupBot/app/UserCommand/subscribe_command.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/logger.js
  VkGroupBot/app/main.js
  VkGroupBot/package.json
Labels: VK, bug, review

#80 fix logs
  VkGroupBot/Dockerfile
  VkGroupBot/app/Handler/audio_message_handler.js
  VkGroupBot/app/Handler/base_handler.js
  VkGroupBot/app/Handler/handler_fabric.js
  VkGroupBot/app/Handler/message_parser.js
  VkGroupBot/app/Handler/text_message_handler.js
  VkGroupBot/app/UserCommand/base_command.js
  VkGroupBot/app/UserCommand/commands_fabric.js
  VkGroupBot/app/UserCommand/create_room_command.js
  VkGroupBot/app/UserCommand/roominfo_command.js
  VkGroupBot/app/UserCommand/rooms_list_command.js
  VkGroupBot/app/UserCommand/send_message_command.js
  VkGroupBot/app/UserCommand/subscribe_command.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/logger.js
  VkGroupBot/app/main.js
  VkGroupBot/package.json
  main-server/main.go
Labels: review

#81 Main server
  main-server/main.go
  main-server/main_test.go
Labels: review

#83 Vk bot bug fix
  VkGroupBot/app/Handler/audio_message_handler.js
  VkGroupBot/app/Handler/base_handler.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/worker.js
  VkGroupBot/package.json
Labels: VK, bug, review

#84 bug fix
  VkGroupBot/app/Handler/audio_message_handler.js
  VkGroupBot/app/Handler/base_handler.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/worker.js
  VkGroupBot/package.json
  main-server/main.go
  main-server/main_test.go
Labels: bug, review

#85 bug fix
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: review

#86 bug fix
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: review

#88 bug fix
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: VK, bug

#90 Bug fix user_message
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: review

#91 BugFix and Logs
  TgBot/bot.py
  TgBot/dialog_flow.py
  TgBot/handlers/base_handler.py
  TgBot/main_server.py
  TgBot/tests/dialog_flow_tests.py
Labels: Telegram, review

#93 Vk bot
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: VK, bug, review

#94 Tg bot
  TgBot/bot.py
  TgBot/handlers/base_handler.py
Labels: review

#95 add ssl
  .travis/deploy.sh
  TgBot/bot.py
  TgBot/handlers/base_handler.py
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: Telegram, bug, high priority, review

#96 room info: fix if statement
  VkGroupBot/app/UserCommand/user_command_handler.js
Labels: VK, bug, review

#97 Development
  VkGroupBot/app/UserCommand/user_command_handler.js
  docker-compose.yml
Labels: CD, VK, bug, high priority, review

#98 Update deploy.sh
  .travis/deploy.sh
Labels: bug, review

#103 Vk bot
  VkGroupBot/app/Bot/bot.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/speech_translator.js
  VkGroupBot/app/tasks_distributor.js
  VkGroupBot/test/test.js
Labels: Tests, VK

#104 add Vk test
  VkGroupBot/app/Bot/bot.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/speech_translator.js
  VkGroupBot/app/tasks_distributor.js
  VkGroupBot/test/test.js
Labels: Tests, VK

#105 bug time.Update
  .travis.yml
Labels: CD, bug

#106 bug with golang
  .travis.yml
Labels: CD, bug
