Repository TeamDevIU/Bot, pull requests merged in 2018-02, with the labels that each got.

#33 TeamDevIU/Bot#19
  Test
Labels: CD, review

#36 TeamDevIU/Bot#19
  VkGroupBot/app/UserCommand/commands_fabric.js
  VkGroupBot/app/UserCommand/user_command_handler.js
  VkGroupBot/app/tasks_distributor.js
  VkGroupBot/package-lock.json
  VkGroupBot/package.json
Labels: CD, VK, review

#39 Tg bot
  .gitignore
  TgBot/.gitignore
  TgBot/bot.py
  TgBot/dialog_flow.py
  TgBot/handlers/__init__.py
  TgBot/handlers/base_handler.py
  TgBot/handlers/text_handler.py
  TgBot/handlers/voice_handler.py
  TgBot/main_server.py
  TgBot/requirements.txt
  TgBot/tests/dialog_flow_tests.py
  TgBot/voice_message.py
Labels: Telegram, review

#40 Исправлен requremenets.txt для сборки на Travis CI
  TgBot/requirements.txt
Labels: review

#41 Merge mainserver and develop
  main-server/checkingStruct.go
  main-server/database.go
  main-server/main.go
  main-server/main_test.go
  main-server/models.go
Labels: MainServer, review
